const images = {
  logo: require('../Images/ir.png'),
  ready: require('../Images/your-app.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  onBoarding1: require('../Images/onboardingIllustration@3x.png'),
  onBoarding2: require('../Images/onboardingIllustration2@3x.png'),
  onBoarding3: require('../Images/onboardingIllustration3@3x.png'),
  buttonBackground: require('../Images/buttonBackground.png'),
  cardBackground: require('../Images/rectangle.png'),
  cardillustration1: require('../Images/cardIllustration.png'),
  cardillustration0: require('../Images/cardIllustration_on@3x.png'),
  backButton: require('../Images/back.png'),
  backButtonWhite: require('../Images/backButtonWhite.png'),
  menuIcon: require('../Images/sidemenu.png'),
  /* messageIcon: require('../Images/messageicon.png'), */
  smsIllustration: require('../Images/smsIllustration@3x.png'),
  messageIcon: require('../Images/messageIcon.png'),
  DotmessageIcon: require('../Images/DotmessageIcon@3x.png'),
  addPhotoCircle: require('../Images/addPhotoWithCircle.png'),
  addPhoto: require('../Images/addUserPhoto.png'),
  editProfileHeader: require('../Images/editProfileHeaderBackground@2x.png'),
  nameIcon: require('../Images/nameImage1.png'),
  emailIcon: require('../Images/emailIcon.png'),
  phoneIcon: require('../Images/phoneIcon.png'),
  discardChangeIcon: require('../Images/discardChangeIcon.png'),
  articleArrow: require('../Images/articleSelectButton.png'),
  likeIcon: require('../Images/likeIcon.png'),
  commentIcon: require('../Images/combinedShape.png'),

  menuTopBekground: require('../Images/navigationDrawerBackground@3x.png'),
  commentAdd: require('../Images/sendCommentIcon.png'),
  avatar: require('../Images/avatar.jpg'),

  user1: require('../Images/dummy/user1.jpg'),
  user2: require('../Images/dummy/user2.jpeg'),
  user3: require('../Images/dummy/user3.jpg'),
  user4: require('../Images/dummy/user4.jpeg'),
  user5: require('../Images/dummy/user6.jpeg'),
  blogImage: require('../Images/dummy/blog.jpeg'),
  blog2: require('../Images/dummy/blog2.jpg'),
  emptyAvailability: require('../Images/emptyAvailability.png'),

}

export default images
